import { serve } from "inngest/next";
import { inngest } from "@/lib/inngest/client";
import {
	agentUpgradeTimeoutCheck,
	autoscalingCheck,
	backupWorkflow,
	buildTriggerWorkflow,
	buildWorkflow,
	certificateRenewal,
	challengeCleanup,
	controlPlaneUpdateCheck,
	expiredDeletedServicesPurge,
	migrationWorkflow,
	notificationDelivery,
	notificationRetention,
	oldBackupsCleanup,
	onDeploymentFailed,
	onRestoreFailed,
	registryArtifactRetention,
	restoreTriggerWorkflow,
	restoreWorkflow,
	rolloutWorkflow,
	scheduledBackupsCheck,
	scheduledDeploymentsCheck,
	serviceDeletionWorkflow,
	serviceCommandRetention,
	serviceCronDispatcher,
	serviceCronWorkflow,
	serviceRestoreWorkflow,
	staleItemsCleanup,
	staleServerCheck,
} from "@/lib/inngest/functions";

export const { GET, POST, PUT } = serve({
	client: inngest,
	functions: [
		autoscalingCheck,
		rolloutWorkflow,
		onDeploymentFailed,
		staleServerCheck,
		serviceCommandRetention,
		scheduledDeploymentsCheck,
		certificateRenewal,
		challengeCleanup,
		scheduledBackupsCheck,
		oldBackupsCleanup,
		staleItemsCleanup,
		controlPlaneUpdateCheck,
		agentUpgradeTimeoutCheck,
		registryArtifactRetention,
		migrationWorkflow,
		backupWorkflow,
		restoreWorkflow,
		onRestoreFailed,
		buildWorkflow,
		buildTriggerWorkflow,
		restoreTriggerWorkflow,
		serviceDeletionWorkflow,
		serviceRestoreWorkflow,
		expiredDeletedServicesPurge,
		notificationDelivery,
		notificationRetention,
		serviceCronDispatcher,
		serviceCronWorkflow,
	],
});
