// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServerId  string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Timestamp string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Sequence  uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_StatusUpdate
	//	*AgentMessage_WorkComplete
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AgentMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AgentMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AgentMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetStatusUpdate() *StatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *AgentMessage) GetWorkComplete() *WorkComplete {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_WorkComplete); ok {
			return x.WorkComplete
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_StatusUpdate struct {
	StatusUpdate *StatusUpdate `protobuf:"bytes,10,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type AgentMessage_WorkComplete struct {
	WorkComplete *WorkComplete `protobuf:"bytes,11,opt,name=work_complete,json=workComplete,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_StatusUpdate) isAgentMessage_Payload() {}

func (*AgentMessage_WorkComplete) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

type ControlPlaneMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlPlaneMessage_Work
	//	*ControlPlaneMessage_Ack
	//	*ControlPlaneMessage_Error
	//	*ControlPlaneMessage_Connected
	//	*ControlPlaneMessage_CaddyConfig
	//	*ControlPlaneMessage_DnsConfig
	Payload       isControlPlaneMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlaneMessage) Reset() {
	*x = ControlPlaneMessage{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneMessage) ProtoMessage() {}

func (x *ControlPlaneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneMessage.ProtoReflect.Descriptor instead.
func (*ControlPlaneMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ControlPlaneMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControlPlaneMessage) GetPayload() isControlPlaneMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlPlaneMessage) GetWork() *WorkItem {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Work); ok {
			return x.Work
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetAck() *Acknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetConnected() *ConnectionAccepted {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Connected); ok {
			return x.Connected
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetCaddyConfig() *CaddyConfig {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_CaddyConfig); ok {
			return x.CaddyConfig
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetDnsConfig() *DnsConfig {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_DnsConfig); ok {
			return x.DnsConfig
		}
	}
	return nil
}

type isControlPlaneMessage_Payload interface {
	isControlPlaneMessage_Payload()
}

type ControlPlaneMessage_Work struct {
	Work *WorkItem `protobuf:"bytes,10,opt,name=work,proto3,oneof"`
}

type ControlPlaneMessage_Ack struct {
	Ack *Acknowledgement `protobuf:"bytes,11,opt,name=ack,proto3,oneof"`
}

type ControlPlaneMessage_Error struct {
	Error *Error `protobuf:"bytes,12,opt,name=error,proto3,oneof"`
}

type ControlPlaneMessage_Connected struct {
	Connected *ConnectionAccepted `protobuf:"bytes,13,opt,name=connected,proto3,oneof"`
}

type ControlPlaneMessage_CaddyConfig struct {
	CaddyConfig *CaddyConfig `protobuf:"bytes,14,opt,name=caddy_config,json=caddyConfig,proto3,oneof"`
}

type ControlPlaneMessage_DnsConfig struct {
	DnsConfig *DnsConfig `protobuf:"bytes,15,opt,name=dns_config,json=dnsConfig,proto3,oneof"`
}

func (*ControlPlaneMessage_Work) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_Ack) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_Error) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_Connected) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_CaddyConfig) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_DnsConfig) isControlPlaneMessage_Payload() {}

type CaddyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*CaddyRoute          `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaddyConfig) Reset() {
	*x = CaddyConfig{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaddyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaddyConfig) ProtoMessage() {}

func (x *CaddyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaddyConfig.ProtoReflect.Descriptor instead.
func (*CaddyConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CaddyConfig) GetRoutes() []*CaddyRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type CaddyRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Upstreams     []string               `protobuf:"bytes,3,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
	Internal      bool                   `protobuf:"varint,4,opt,name=internal,proto3" json:"internal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaddyRoute) Reset() {
	*x = CaddyRoute{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaddyRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaddyRoute) ProtoMessage() {}

func (x *CaddyRoute) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaddyRoute.ProtoReflect.Descriptor instead.
func (*CaddyRoute) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CaddyRoute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaddyRoute) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CaddyRoute) GetUpstreams() []string {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

func (x *CaddyRoute) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     *Resources             `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
	PublicIp      string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StatusUpdate) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *StatusUpdate) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryTotalMb int32                  `protobuf:"varint,2,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	DiskTotalGb   int32                  `protobuf:"varint,3,opt,name=disk_total_gb,json=diskTotalGb,proto3" json:"disk_total_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Resources) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Resources) GetMemoryTotalMb() int32 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *Resources) GetDiskTotalGb() int32 {
	if x != nil {
		return x.DiskTotalGb
	}
	return 0
}

type WorkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *WorkItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Logs          string                 `protobuf:"bytes,3,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkComplete) Reset() {
	*x = WorkComplete{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkComplete) ProtoMessage() {}

func (x *WorkComplete) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkComplete.ProtoReflect.Descriptor instead.
func (*WorkComplete) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WorkComplete) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *WorkComplete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkComplete) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Acknowledgement) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Acknowledgement) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fatal         bool                   `protobuf:"varint,3,opt,name=fatal,proto3" json:"fatal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

type ConnectionAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionAccepted) Reset() {
	*x = ConnectionAccepted{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionAccepted) ProtoMessage() {}

func (x *ConnectionAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionAccepted.ProtoReflect.Descriptor instead.
func (*ConnectionAccepted) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectionAccepted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DnsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*DnsRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsConfig) Reset() {
	*x = DnsConfig{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsConfig) ProtoMessage() {}

func (x *DnsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsConfig.ProtoReflect.Descriptor instead.
func (*DnsConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DnsConfig) GetRecords() []*DnsRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type DnsRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecord) Reset() {
	*x = DnsRecord{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecord) ProtoMessage() {}

func (x *DnsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecord.ProtoReflect.Descriptor instead.
func (*DnsRecord) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DnsRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DnsRecord) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xb8\x02\n" +
	"\fAgentMessage\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12:\n" +
	"\rstatus_update\x18\n" +
	" \x01(\v2\x13.agent.StatusUpdateH\x00R\fstatusUpdate\x12:\n" +
	"\rwork_complete\x18\v \x01(\v2\x13.agent.WorkCompleteH\x00R\fworkComplete\x120\n" +
	"\theartbeat\x18\f \x01(\v2\x10.agent.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xdc\x02\n" +
	"\x13ControlPlaneMessage\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12%\n" +
	"\x04work\x18\n" +
	" \x01(\v2\x0f.agent.WorkItemH\x00R\x04work\x12*\n" +
	"\x03ack\x18\v \x01(\v2\x16.agent.AcknowledgementH\x00R\x03ack\x12$\n" +
	"\x05error\x18\f \x01(\v2\f.agent.ErrorH\x00R\x05error\x129\n" +
	"\tconnected\x18\r \x01(\v2\x19.agent.ConnectionAcceptedH\x00R\tconnected\x127\n" +
	"\fcaddy_config\x18\x0e \x01(\v2\x12.agent.CaddyConfigH\x00R\vcaddyConfig\x121\n" +
	"\n" +
	"dns_config\x18\x0f \x01(\v2\x10.agent.DnsConfigH\x00R\tdnsConfigB\t\n" +
	"\apayload\"8\n" +
	"\vCaddyConfig\x12)\n" +
	"\x06routes\x18\x01 \x03(\v2\x11.agent.CaddyRouteR\x06routes\"n\n" +
	"\n" +
	"CaddyRoute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1c\n" +
	"\tupstreams\x18\x03 \x03(\tR\tupstreams\x12\x1a\n" +
	"\binternal\x18\x04 \x01(\bR\binternal\"[\n" +
	"\fStatusUpdate\x12.\n" +
	"\tresources\x18\x01 \x01(\v2\x10.agent.ResourcesR\tresources\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\"t\n" +
	"\tResources\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12&\n" +
	"\x0fmemory_total_mb\x18\x02 \x01(\x05R\rmemoryTotalMb\x12\"\n" +
	"\rdisk_total_gb\x18\x03 \x01(\x05R\vdiskTotalGb\"H\n" +
	"\bWorkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"S\n" +
	"\fWorkComplete\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04logs\x18\x03 \x01(\tR\x04logs\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"J\n" +
	"\x0fAcknowledgement\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"K\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05fatal\x18\x03 \x01(\bR\x05fatal\"3\n" +
	"\x12ConnectionAccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"7\n" +
	"\tDnsConfig\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.agent.DnsRecordR\arecords\"1\n" +
	"\tDnsRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips2N\n" +
	"\fAgentService\x12>\n" +
	"\aConnect\x12\x13.agent.AgentMessage\x1a\x1a.agent.ControlPlaneMessage(\x010\x01B%Z#techulus/cloud-agent/internal/protob\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),        // 0: agent.AgentMessage
	(*ControlPlaneMessage)(nil), // 1: agent.ControlPlaneMessage
	(*CaddyConfig)(nil),         // 2: agent.CaddyConfig
	(*CaddyRoute)(nil),          // 3: agent.CaddyRoute
	(*StatusUpdate)(nil),        // 4: agent.StatusUpdate
	(*Resources)(nil),           // 5: agent.Resources
	(*WorkItem)(nil),            // 6: agent.WorkItem
	(*WorkComplete)(nil),        // 7: agent.WorkComplete
	(*Heartbeat)(nil),           // 8: agent.Heartbeat
	(*Acknowledgement)(nil),     // 9: agent.Acknowledgement
	(*Error)(nil),               // 10: agent.Error
	(*ConnectionAccepted)(nil),  // 11: agent.ConnectionAccepted
	(*DnsConfig)(nil),           // 12: agent.DnsConfig
	(*DnsRecord)(nil),           // 13: agent.DnsRecord
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: agent.AgentMessage.status_update:type_name -> agent.StatusUpdate
	7,  // 1: agent.AgentMessage.work_complete:type_name -> agent.WorkComplete
	8,  // 2: agent.AgentMessage.heartbeat:type_name -> agent.Heartbeat
	6,  // 3: agent.ControlPlaneMessage.work:type_name -> agent.WorkItem
	9,  // 4: agent.ControlPlaneMessage.ack:type_name -> agent.Acknowledgement
	10, // 5: agent.ControlPlaneMessage.error:type_name -> agent.Error
	11, // 6: agent.ControlPlaneMessage.connected:type_name -> agent.ConnectionAccepted
	2,  // 7: agent.ControlPlaneMessage.caddy_config:type_name -> agent.CaddyConfig
	12, // 8: agent.ControlPlaneMessage.dns_config:type_name -> agent.DnsConfig
	3,  // 9: agent.CaddyConfig.routes:type_name -> agent.CaddyRoute
	5,  // 10: agent.StatusUpdate.resources:type_name -> agent.Resources
	13, // 11: agent.DnsConfig.records:type_name -> agent.DnsRecord
	0,  // 12: agent.AgentService.Connect:input_type -> agent.AgentMessage
	1,  // 13: agent.AgentService.Connect:output_type -> agent.ControlPlaneMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_StatusUpdate)(nil),
		(*AgentMessage_WorkComplete)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlPlaneMessage_Work)(nil),
		(*ControlPlaneMessage_Ack)(nil),
		(*ControlPlaneMessage_Error)(nil),
		(*ControlPlaneMessage_Connected)(nil),
		(*ControlPlaneMessage_CaddyConfig)(nil),
		(*ControlPlaneMessage_DnsConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
