FROM node:22-alpine AS builder
RUN corepack enable pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm grpc:build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist/grpc ./dist/grpc
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
EXPOSE 50051
CMD ["node", "dist/grpc/server.mjs"]
